services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_stock_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - stock_network

  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_server
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/workspace 
    depends_on:
      - postgres     
    networks:
      - stock_network
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload

  dozzle:
    image: amir20/dozzle:latest
    container_name: log_viewer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8080:8080"
    depends_on:
      - api-server

volumes:
  postgres_data:

networks:
  stock_network:
    driver: bridge