name: Continuous Integration (Test Suite)

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: my_stock_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update && sudo apt-get install -y postgresql-client

    - name: Initialize Database Schema
      env:
        PGPASSWORD: postgres
      run: |
        psql -h localhost -U postgres -d my_stock_db -f init.sql

    - name: Run Pytest
      env:
        USE_MOCK_API: "true"
        DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/my_stock_db"
      run: |
        pytest